repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "cafd550"
    hooks:
      - id: prettier
        files: \.(css|less|scss|json|yaml|yml|html|md|mdx|js|jsx|ts|tsx|graphql|gql|vue|svelte|toml)$
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
      - id: isort
        name: isort
        language: system
        entry: isort
        args: ["--profile", "black"]
        types: [python]
      - id: ruff
        name: ruff
        language: system
        entry: ruff --fix
        types: [python]
      - id: mypy
        name: mypy
        language: system
        entry: mypy denoisers
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        language: system
        entry: python -m pytest
        pass_filenames: false
        always_run: true
      - id: pydocstyle
        name: pydocstyle
        description: pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
        entry: pydocstyle --convention=google --add-ignore=D107
        language: python
        types: [python]
