[build-system]
requires = [
    "pip",
    "setuptools>=61.0",
    "wheel",
    "pesq",
    "torch>=2.0.0",
    "torchaudio>=2.0.0",
    "pytorch-lightning>=2.0.0",
    "transformers",
    "wandb",
    "soundboard",
]
build-backend = "setuptools.build_meta"

[project]
name = "denoisers"
version = "0.1.5"
authors = [
  { name="Will Rice", email="wrice20@gmail.com" },
]
description = "A package for training audio denoisers"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/will-rice/denoisers"
"Bug Tracker" = "https://github.com/will-rice/denoisers/issues"

[tool.isort]
known_first_party = ["denoisers"]

[tool.ruff]
ignore-init-module-imports = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]
